[package]
name = "dioxus_markdown"
version = "0.3.0-alpha.2"
edition = "2021"

[dependencies]
dioxus = "0.6.0-alpha.2"
pulldown-cmark = "0.9.3"

[dev-dependencies]
dioxus = { version = "0.6.0-alpha.2", features = ["desktop"] }
